### PR TITLE
Adding apt packages to documentation

### PR DESCRIPTION
**Pull request by DXCanas**
Found some missing `apt` packages while going through the installation on Ubuntu 20, thought I'd add to the docs with your PR

### CODE REVIEW

**Comment by jredrejo** [comment]
@DXCanas I have checked I don't have installed in my system (Ubuntu 20.04) libcairo2-dev nor libjpeg8-dev (I have libjpeg62-dev) and I can install it all, could you check if installing libjpeg62-dev you don't need these two?

**Comment by DXCanas** [comment]
I'll check on that - I don't have `libjpeg62` installed at all, and this system was set up just a few days ago. I had to install the same programs on my last distro while setting up studio.

**Comment by DXCanas** [comment]
I've `apt purged` the packages you mentioned, and `pip install --no-cache` the requirements in a fresh venv, and things seem to be working ok now :upside_down_face:. I can't tell you why, but I swear that things wouldn't install until after I installed the packages, even if they're gone now haha. I thought about replicating in docker, but I don't think that would be the same. And, to be honest, I don't care enough to spin up a new VM and try again in a fresh environment there.

I remember the issues coming from Pillow:

https://pillow.readthedocs.io/en/latest/installation.html#building-on-linux

and another library, I think matplotlib. Though I can't remember for sure.

**Comment by DXCanas** [comment]
Closing this probably-stale branch. Will revisit next time I do a cold install.

**Pull request closed without merging**
